version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./config:/etc/prometheus"
      - "./data:/prometheus"
    networks:
      - prom-network

networks:
  prom-network:
    name: prom-network
    driver: bridge
